version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    networks:
      - backend-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    expose:
      - "8000"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  legecy_ai:
    build:
      context: ./legecy_ai
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - backend-network
      - frontend-network

networks:
  backend-network:
  frontend-network:

